### ISSUE TITLE
username not derrived from config.yaml

### ISSUE THREAD

**Issue by rob-c** [opensciencegrid/xrootd-monitoring-shoveler#11]
Hi,

After doing some initial testing I was under the impression from the example config file that the username and password used for amqp auth'n was derrived from the server url line:
https://github.com/opensciencegrid/xrootd-monitoring-shoveler/blob/50a212f2d75327cbeeca4043af096f4158f8d39c/config/config.yaml#L2

After playing with an example build and running through the code I found I had to make hard-code changes to alter the username and the password is found in the 'token' file.

Would it be possible to replace this with something similar to:

```
amqp:
  url: amqps://example.com/vhost
  username: shoveler-user
  exchange: shoveler-exchange
  topic: shoveler-topic
  token_location: /etc/xrootd-monitoring-shoveler/token
```

Thanks,

Rob
